# docker-compose.yml (Versión final con sustitución de variables)
version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env # El contenedor 'db' carga estas variables directamente

  api:
    image: daldeoscoder/icinema-api:1.0 
    ports:
      - "8000:8000"
    environment:
      # docker-compose REEMPLAZA estas variables ANTES de iniciar el contenedor
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

volumes:
  postgres_data: